name: Deploy to Netlify
on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"

  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy from."
        required: true
        default: "main"

defaults:
  run:
    working-directory: api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/thealty
            git pull
            docker compose pull --include-deps
            docker compose build --no-cache
            docker-compose --file docker-compose.yml --file docker-compose.prod.yml up --detach

